---
version: "3"
services:
 devopsdb:  
   image: dbimage
   ports:
     - "3306"

 application:
   image: appimage
   ports:
     - "8080"
   depends_on:
     - "devopsdb"
   deploy:
     - replicas: 2
